[2024-11-06T10:50:32.555+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T10:50:32.573+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.process_user manual__2024-11-06T10:50:20.501686+00:00 [queued]>
[2024-11-06T10:50:32.582+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.process_user manual__2024-11-06T10:50:20.501686+00:00 [queued]>
[2024-11-06T10:50:32.583+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-06T10:50:32.596+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): process_user> on 2024-11-06 10:50:20.501686+00:00
[2024-11-06T10:50:32.604+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=94) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T10:50:32.606+0000] {standard_task_runner.py:72} INFO - Started process 96 to run task
[2024-11-06T10:50:32.606+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'manual__2024-11-06T10:50:20.501686+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/user-processing.py', '--cfg-path', '/tmp/tmpwah3tk9n']
[2024-11-06T10:50:32.609+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask process_user
[2024-11-06T10:50:32.825+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.process_user manual__2024-11-06T10:50:20.501686+00:00 [running]> on host a664c8dd9839
[2024-11-06T10:50:32.909+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='process_user' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T10:50:20.501686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T10:50:20.501686+00:00'
[2024-11-06T10:50:32.911+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T10:50:32.944+0000] {logging_mixin.py:190} INFO - <class 'dict'>
[2024-11-06T10:50:32.973+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-06T10:50:32.986+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T10:50:32.987+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=process_user, run_id=manual__2024-11-06T10:50:20.501686+00:00, execution_date=20241106T105020, start_date=20241106T105032, end_date=20241106T105032
[2024-11-06T10:50:33.022+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-06T10:50:33.209+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-06T10:50:33.211+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
